'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Check,Coins,Lightbulb,RotateCcw,Undo2,Move,Package,Star} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {CatMascot} from '@/components/cat-mascot';
import {complete,deliveredCount,deltas,movePuzzle,puzzleHint,puzzles,startPuzzle,stuckCrate,validatePuzzle,type Cell,type Direction,type PuzzleState} from '@/lib/cat-puzzles';
import {emptyProgress,totalPoints,type StreetProgress} from '@/lib/cat-street';
import type {PuzzleScene} from '@/lib/cat-puzzle-scene';
type Round={history:PuzzleState[];directions:Direction[]};
type Result={progress:StreetProgress;puzzleScores:number[]};
const shortNames=['The café','The bakery','The neighbours','The customers','The results'];
const directionNames:Record<Direction,string>={U:'up',R:'right',D:'down',L:'left'};
export function CatPuzzleGame(){
 const initial=()=>puzzles.map((_,i)=>({history:[startPuzzle(i)],directions:[] as Direction[]}));
 const [rounds,setRounds]=useState<Round[]>(initial),roundsRef=useRef(rounds),[stage,setStage]=useState(0),stageRef=useRef(stage);stageRef.current=stage;
 const [progress,setProgress]=useState<StreetProgress>({...emptyProgress,scores:[0,0,0,0,0]}),[best,setBest]=useState([0,0,0,0,0]),data=useRef<Result>({progress,puzzleScores:best});
 const [ready,setReady]=useState(false),[sceneError,setSceneError]=useState(''),[hinting,setHinting]=useState(false),[message,setMessage]=useState('Push the parcel onto a glowing circle. You can push, but you can’t pull.');
 const canvasHost=useRef<HTMLDivElement>(null),board=useRef<HTMLDivElement>(null),view=useRef<PuzzleScene|null>(null),cellAction=useRef<(cell:Cell)=>void>(()=>{}),hintRequest=useRef(0),lastMove=useRef(0);
 const round=rounds[stage],state=round.history.at(-1)!,puzzle=puzzles[stage],won=complete(stage,state),points=totalPoints(progress),delivered=deliveredCount(stage,state),solved=best.filter(s=>s>=150).length;
 function accept(result:Result){data.current=result;setProgress(result.progress);setBest(result.puzzleScores||[0,0,0,0,0])}
 useEffect(()=>{let cancelled=false;const host=canvasHost.current;if(!host)return;void import('@/lib/cat-puzzle-scene').then(async({createPuzzleScene})=>{const scene=await createPuzzleScene(host,cell=>cellAction.current(cell));if(cancelled){scene.dispose();return}view.current=scene;scene.show(stageRef.current,roundsRef.current[stageRef.current].history.at(-1)!);setReady(true)}).catch(()=>{if(!cancelled)setSceneError('The puzzle view could not open. Please reload in a browser with WebGL enabled.')});return()=>{cancelled=true;view.current?.dispose();view.current=null}},[]);
 useEffect(()=>{view.current?.show(stage,state)},[stage,state,ready]);
 useEffect(()=>()=>{hintRequest.current++},[]);
 function focusBoard(){requestAnimationFrame(()=>board.current?.focus({preventScroll:true}))}
 function changeRound(index:number,next:Round){const all=roundsRef.current.map((r,i)=>i===index?next:r);roundsRef.current=all;setRounds(all);hintRequest.current++;setHinting(false);view.current?.hint(null)}
 function finish(index:number,moves:string){view.current?.celebrate();const score=validatePuzzle(index,moves).score;const scores=data.current.progress.scores.map((v,i)=>i===index?Math.max(v,score):v),puzzleScores=data.current.puzzleScores.map((v,i)=>i===index?Math.max(v,score):v);accept({progress:{scores,unlocked:scores.filter(s=>s>=150).length,revision:0},puzzleScores})}
 function step(direction:Direction){const index=stageRef.current,r=roundsRef.current[index],current=r.history.at(-1)!;if(!ready||complete(index,current)||performance.now()-lastMove.current<95)return;lastMove.current=performance.now();if(r.directions.length>=400){setMessage('A shorter route may help. Undo a few moves or restart this puzzle.');return}const next=movePuzzle(index,current,direction);if(!next){setMessage('That way is blocked. Try getting to another side of the parcel.');return}changeRound(index,{history:[...r.history,next],directions:[...r.directions,direction]});if(complete(index,next)){setMessage('Everything is in place!');finish(index,[...r.directions,direction].join(''))}else if(stuckCrate(index,next))setMessage('A parcel in a corner can’t come back out. Undo is your friend.');else if(deliveredCount(index,next)>deliveredCount(index,current)){setMessage(puzzles[index].delivered);view.current?.celebrate()}else setMessage('Find a way around the parcel, then give it a push.')}
 cellAction.current=cell=>{const current=roundsRef.current[stageRef.current].history.at(-1)!,dx=cell.x-current.cat.x,dy=cell.y-current.cat.y;if(Math.abs(dx)+Math.abs(dy)===1)step(dx===1?'R':dx===-1?'L':dy===1?'D':'U');else setMessage('Tap a square next to the Cat, or use the arrow buttons.');focusBoard()};
 function undo(){const index=stageRef.current,r=roundsRef.current[index];if(r.history.length<2||complete(index,r.history.at(-1)!))return;changeRound(index,{history:r.history.slice(0,-1),directions:r.directions.slice(0,-1)});setMessage('Back one step. Try a different way.');focusBoard()}
 function restart(){changeRound(stage,{history:[startPuzzle(stage)],directions:[]});setMessage('A fresh start. Take your time.');focusBoard()}
 function choose(index:number){hintRequest.current++;setHinting(false);setStage(index);setMessage('Push each parcel onto a glowing circle. Work out which side to approach from.');focusBoard()}
 async function hint(){if(hinting||won)return;const request=++hintRequest.current;const index=stage,current=state;setHinting(true);setMessage('Let’s look for a way through…');try{const direction=await puzzleHint(index,current);if(request!==hintRequest.current)return;if(direction){const d=deltas[direction];view.current?.hint({x:current.cat.x+d.x,y:current.cat.y+d.y});setMessage('Try moving '+directionNames[direction]+'. The highlighted square is your next step.')}else setMessage('This route needs a rethink. Undo a push, or restart for another try.')}finally{if(request===hintRequest.current){setHinting(false);focusBoard()}}}
 return <div className="puzzle-page"><section className="puzzle-game" aria-label="Cat Street delivery puzzles"><header className="puzzle-top"><Link href="/" className="puzzle-brand"><CatMascot/><span>Cat Street</span></Link><div><span className="puzzle-saved">Practice points</span><span className="puzzle-wallet"><Coins size={19}/><strong>{points}</strong><small>/ 1,000</small></span></div></header>
 <div className="puzzle-layout"><div className="puzzle-play"><div className="puzzle-title"><div><h1>{puzzle.name}</h1><p>{puzzle.task}</p></div><span><Package size={17}/>{delivered} / {state.crates.length} delivered</span></div>
 <div className="puzzle-board-wrap" ref={board} tabIndex={0} role="application" aria-label={`${puzzle.name}. Use arrow keys or W A S D to move the Cat. Push parcels onto glowing circles. Z undoes a move.`} onKeyDown={e=>{if(e.altKey||e.metaKey||e.ctrlKey)return;const key:Record<string,Direction>={ArrowUp:'U',KeyW:'U',ArrowRight:'R',KeyD:'R',ArrowDown:'D',KeyS:'D',ArrowLeft:'L',KeyA:'L'};if(key[e.code]){e.preventDefault();step(key[e.code])}else if(e.code==='KeyZ'){e.preventDefault();undo()}}}>
 <div className="puzzle-scene" ref={canvasHost}/>{!ready&&<div className="puzzle-loading"><CatMascot/><p>{sceneError||'Getting the neighbourhood ready…'}</p></div>}
 <div className="puzzle-counters"><span>{state.moves} moves</span><span><Star size={15}/> Aim for {puzzle.par} or fewer</span></div>
 <div className="puzzle-pad" aria-label="Move the Cat"><Button variant="ghost" aria-label="Move up" onClick={()=>{step('U');focusBoard()}}><ArrowUp/></Button><Button variant="ghost" aria-label="Move left" onClick={()=>{step('L');focusBoard()}}><ArrowLeft/></Button><Button variant="ghost" aria-label="Move down" onClick={()=>{step('D');focusBoard()}}><ArrowDown/></Button><Button variant="ghost" aria-label="Move right" onClick={()=>{step('R');focusBoard()}}><ArrowRight/></Button></div>
 </div><div className="puzzle-tools"><Button variant="outline" onClick={undo} disabled={state.moves===0||won}><Undo2 size={17}/> Undo</Button><Button variant="outline" onClick={restart}><RotateCcw size={17}/> Restart</Button><Button variant="outline" onClick={()=>void hint()} disabled={hinting||won||!ready}><Lightbulb size={17}/>{hinting?'Thinking…':'A little hint'}</Button></div><p className="puzzle-message" aria-live="polite">{message}</p>
 </div><aside className="puzzle-companion">
 {won?<div className="puzzle-win"><div className="puzzle-success-mark"><Check size={28}/></div><h2>Nicely delivered!</h2><p>{puzzle.lesson}</p><div className="puzzle-earned"><Coins size={21}/><strong>{state.moves<=puzzle.par?200:150}</strong><span>practice points</span></div><small>{state.moves<=puzzle.par?'That includes the 50-point move bonus.':'Finish in '+puzzle.par+' moves or fewer to earn the extra 50 points.'} Replays improve your best; points aren’t added twice.</small>{stage<4?<Button className="button purple" onClick={()=>choose(stage+1)}>Try the next puzzle <ArrowRight size={17}/></Button>:<Button className="button purple" onClick={()=>choose(0)}>Play again <RotateCcw size={17}/></Button>}</div>:<div className="puzzle-how"><CatMascot/><h2>A little thinking.<br/>A gentle push.</h2><p>Get behind a parcel and push it onto a glowing circle. Clear a path before you move the next one.</p><p>Stuck? Undo a move, ask for a hint or start again. There’s no timer.</p><span><Move size={17}/> Arrow keys, W A S D or the buttons below the board.</span></div>}
 <div className="puzzle-levels"><h3>Where shall we go?</h3>{puzzles.map((p,i)=><button key={p.name} className={stage===i?'selected':''} onClick={()=>choose(i)} aria-current={stage===i?'step':undefined}><span className="puzzle-level-dot" style={{background:p.color}}>{best[i]>=150?<Check size={15}/>:<Package size={15}/>}</span><span>{shortNames[i]}</span><small>{best[i]===200?<Star size={15}/>:best[i]>=150?'Done':stage===i?'Playing':''}</small></button>)}<p>{solved} of 5 puzzles completed in this practice session.</p></div>
 </aside></div>
 <footer className="puzzle-foot"><p>Play for fun. Your scores stay in this session and reset when you leave the page.</p></footer>
 </section><p className="puzzle-reward-note">150 points for each puzzle, plus 50 for finishing within its move target. Best scores count once, up to 1,000 points in a session.</p></div>
}
