'use client';
import {useState} from 'react';
import {ChoiceGroup as Tabs,ChoiceList as TabsList,ChoiceItem as TabsTrigger} from '@/components/choice-group';
const process=[
 {name:'Understand',title:'First, your world.',you:'Your business details, customer questions and what you want to work towards.',cat:'Questions about your neighbourhood, current presence and the next customer action.',agree:'The priority, the audience and what needs a closer look.'},
 {name:'Plan',title:'Give the idea a direction.',you:'Useful product information, upcoming occasions and your preferred tone.',cat:'A content direction, channel roles and a suggested sequence of activity.',agree:'The scope, responsibilities, timing and how the work will be reviewed.'},
 {name:'Create',title:'Bring the real business into view.',you:'Access to the right people, products and business material.',cat:'Draft stories and creative work based on the agreed direction.',agree:'The content version ready for review and any factual details to confirm.'},
 {name:'Review',title:'One clear version. Shared confidence.',you:'Consolidated feedback and confirmation of facts and required permissions.',cat:'An internal review, revisions where agreed and a final version to approve.',agree:'Client approval and publishing arrangements before sharing.'},
 {name:'Learn',title:'Let the response shape what’s next.',you:'Relevant enquiry feedback and confirmed bookings, visits or sales where available.',cat:'A review of completed activity, available response and useful observations.',agree:'What to continue, what to change and the next priorities.'}
];
export function ProcessTour(){const [step,setStep]=useState('0');const p=process[Number(step)];return <section className="process-tour container"><div className="section-heading"><div><h2>Everyone knows<br/><em>their next step.</em></h2></div><p>Choose a stage to see what we bring to the table together.</p></div><Tabs value={step} onValueChange={setStep}><TabsList className="process-tour-tabs">{process.map((p,i)=><TabsTrigger key={p.name} value={String(i)}><span>0{i+1}</span>{p.name}</TabsTrigger>)}</TabsList></Tabs><div className="process-tour-detail" aria-live="polite"><div><span className="tour-big-number">0{Number(step)+1}</span><h3>{p.title}</h3></div><dl><div><dt>You bring</dt><dd>{p.you}</dd></div><div><dt>We prepare</dt><dd>{p.cat}</dd></div><div><dt>We agree together</dt><dd>{p.agree}</dd></div></dl></div></section>}
