'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Shuffle,Sparkles,MapPin,MousePointer2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {CatIcon} from '@/components/shared';
import {GrowthEnquiry} from '@/components/growth-enquiry';
import {industries} from '@/lib/content';
import {contact} from '@/lib/contact';
import {gsap} from '@/lib/gsap';
const angles:Record<string,string[]>={food:['Good mornings. Great neighbours.','A little pause. A lot of flavour.','Meet the maker behind your favourite.'],retail:['Found your next favourite? It’s nearby.','A little new. A little you.','The detail you’ll want to see up close.'],beauty:['Your first visit. Already a familiar feeling.','A little time, just for you.','Meet the person behind the appointment.'],fitness:['First day. First rep. Your pace.','Your next chapter starts with one session.','A familiar face for your first workout.'],education:['Big questions. Clear next steps.','Your next chapter could start nearby.','Meet the people you’ll learn from.'],services:['Small fix. Big sigh of relief.','The name to know, when you need a hand.','A little local know-how goes a long way.']};
const actions:Record<string,string>={visits:'Come take a closer look.',enquiries:'Ask us your first question.',launch:'Meet your new neighbour.'};
export function GrowthHero(){const [industry,setIndustry]=useState('food'),[goal,setGoal]=useState('enquiries'),[angle,setAngle]=useState(0);const i=industries.find(x=>x.id===industry)!;const line=angles[industry][angle];return <section className="playful-growth-hero"><div className="container growth-playful-grid"><div className="growth-playful-copy"><h1>Let’s make<br/>the locals<br/><em>look twice.</em></h1><p>Real business. Local personality. A clear reason to say hello. Play with a direction for your business.</p><CampaignToy industry={industry} onIndustry={setIndustry} angle={angle} onShuffle={()=>setAngle((angle+1)%3)} goal={goal}/><a className="text-link" href={contact.phoneHref}>Talk it through: {contact.phone} <ArrowUpRight size={17}/></a></div><div className="growth-form-anchor" id="growth-enquiry"><GrowthEnquiry businessType={industry} creativeIdea={`${line} ${actions[goal]}`} onGoalChange={setGoal}/><p className="growth-reassurance"><MapPin size={17}/> Local understanding. A chapter of Mindstory.</p></div></div></section>}
function CampaignToy({industry,onIndustry,angle,onShuffle,goal}:{industry:string;onIndustry:(s:string)=>void;angle:number;onShuffle:()=>void;goal:string}){const card=useRef<HTMLDivElement>(null);const i=industries.find(x=>x.id===industry)!;useEffect(()=>{if(!card.current||matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.reducedMotion==='true')return;const tween=gsap.fromTo(card.current,{rotationY:-15,rotation:-2,y:12,scale:.97},{rotationY:0,rotation:1,y:0,scale:1,duration:.65,ease:'back.out(1.4)'});return()=>{tween.kill()}},[industry,angle,goal]);return <div className="campaign-toy"><div className="toy-toolbar"><label htmlFor="toy-business">Make it feel like your business</label><select id="toy-business" value={industry} onChange={e=>onIndustry(e.target.value)}>{industries.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></div><div className="toy-perspective"><div ref={card} className={'toy-card toy-'+industry} aria-live="polite"><div><span><CatIcon name={i.icon} size={20}/>{i.name}</span><span>CONCEPT / 0{angle+1}</span></div><h2>{angles[industry][angle]}</h2><footer><span>{actions[goal]}</span><ArrowUpRight size={27}/></footer></div></div><div className="toy-bottom"><span><MousePointer2 size={16}/> A starting idea. Make it your own.</span><Button variant="ghost" onClick={onShuffle}><Shuffle size={17}/> Try another angle</Button></div></div>}
export function HomePlayground(){const [industry,setIndustry]=useState('retail'),[angle,setAngle]=useState(0);return <section className="home-playground"><div className="container home-playground-grid"><div><h2>A little play.<br/><em>A fresh point of view.</em></h2><p>Choose a business. Shuffle the angle. See how a familiar detail can turn into a local introduction.</p><Link href="/local-growth" className="text-link">Find your growth direction <ArrowUpRight size={18}/></Link></div><CampaignToy industry={industry} onIndustry={setIndustry} angle={angle} onShuffle={()=>setAngle((angle+1)%3)} goal="visits"/></div></section>}
