'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,CheckCircle2,Loader2,Phone,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Checkbox} from '@/components/ui/checkbox';
import {contact} from '@/lib/contact';
const directions=[{id:'visits',label:'More visits',title:'Make the visit feel worth it.',points:['Show a real reason to drop in.','Keep opening hours and directions clear.','Connect local content to your location.'],services:['local-discovery','content-production']},{id:'enquiries',label:'More enquiries',title:'Make the next conversation easy.',points:['Lead with one clear customer need.','Use a focused message and contact route.','Agree who responds and records the outcome.'],services:['local-campaigns','local-strategy']},{id:'launch',label:'A new opening',title:'Give your opening a local introduction.',points:['Confirm the date, place and key details.','Introduce the people and experience.','Coordinate content and local promotion.'],services:['local-strategy','creator-collaborations']}];
export function GrowthEnquiry({businessType='other',creativeIdea='',onGoalChange}:{businessType?:string;creativeIdea?:string;onGoalChange?:(goal:string)=>void}={}){const [goal,setGoal]=useState('enquiries'),[id,setId]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState('');useEffect(()=>setId(crypto.randomUUID()),[]);const direction=directions.find(x=>x.id===goal)!;
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;if(!consent){setError('Please agree to share your details for this enquiry.');return}const f=new FormData(e.currentTarget);if(f.get('company_website'))return;setBusy(true);setError('');const query=new URLSearchParams(window.location.search);const attribution=Object.fromEntries(['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].map(k=>[k,(query.get(k)||'').slice(0,150)]));try{const response=await fetch('/api/briefs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submissionId:id,name:f.get('name'),business:f.get('business'),email:f.get('email'),phone:f.get('phone')||'',location:f.get('location'),industry:businessType,goal,services:direction.services,requirement:`Local growth enquiry: ${direction.label}. ${direction.points.join(' ')} Creative starting point: ${creativeIdea}`,timing:'Let’s discuss',links:'',budget:f.get('budget')||'',assessment:JSON.stringify({source:'/local-growth',goal,...attribution}),consent:true})});const result=await response.json() as {saved?:boolean;reference?:string;error?:string};if(!response.ok||!result.saved||!result.reference)throw new Error(result.error||'Your enquiry could not be saved. Please try again.');setReference(result.reference)}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Your details are still here.')}finally{setBusy(false)}}
if(reference)return <div className="growth-form-success" role="status"><CheckCircle2 size={44}/><h2>Your enquiry<br/>is saved.</h2><p>Your focus: <strong>{direction.label.toLowerCase()}</strong>. Keep this reference for your conversation with Viral Cat.</p><strong className="growth-reference">{reference}</strong><ul>{direction.points.map(p=><li key={p}><Check size={17}/>{p}</li>)}</ul><Button asChild className="button purple"><a href={contact.phoneHref}><Phone size={18}/> Talk to Viral Cat</a></Button><Link href="/cat-lab/check" className="text-link">Try the local presence check <ArrowUpRight size={16}/></Link></div>;
return <div className="growth-enquiry"><div className="growth-form-top"><span className="quiet-caption">Tell us where you’d like to start</span><h2>What would help<br/>your business most?</h2><p>Choose your goal. See a direction. Tell us where to begin.</p></div><Tabs value={goal} onValueChange={v=>{if(!busy){setGoal(v);onGoalChange?.(v)}}}><TabsList className="growth-goals">{directions.map(d=><TabsTrigger key={d.id} value={d.id}>{d.label}</TabsTrigger>)}</TabsList>{directions.map(d=><TabsContent key={d.id} value={d.id}><div className="growth-goal-insight"><strong>{d.title}</strong><ul>{d.points.map(p=><li key={p}><Check size={15}/>{p}</li>)}</ul></div></TabsContent>)}</Tabs><form onSubmit={submit}><fieldset disabled={busy}><legend className="sr-only">Your business and contact details</legend><div className="form-grid">{[{key:'name',label:'Your name',auto:'name',max:120},{key:'business',label:'Business name',auto:'organization',max:150},{key:'email',label:'Email address',auto:'email',max:200},{key:'location',label:'Town or neighbourhood',auto:'address-level2',max:150}].map(f=><div className="field" key={f.key}><Label htmlFor={'growth-'+f.key}>{f.label} *</Label><Input id={'growth-'+f.key} name={f.key} type={f.key==='email'?'email':'text'} required minLength={f.key==='email'?undefined:2} maxLength={f.max} autoComplete={f.auto}/></div>)}</div><div className="field"><Label htmlFor="growth-phone">Phone number <span>(optional)</span></Label><Input id="growth-phone" name="phone" type="tel" autoComplete="tel" maxLength={40}/></div><div className="field"><Label htmlFor="growth-budget">Monthly budget <span>(optional)</span></Label><Input id="growth-budget" name="budget" list="growth-budget-options" maxLength={60} placeholder="Choose a range or type your own"/><datalist id="growth-budget-options"><option value="Under ₹25,000/month"/><option value="₹25,000 – ₹50,000/month"/><option value="₹50,000 – ₹1,00,000/month"/><option value="Above ₹1,00,000/month"/><option value="Let’s discuss"/></datalist></div><div className="form-honey" aria-hidden="true"><label>Leave empty<input name="company_website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>I agree to share these details for my enquiry. <Link href="/privacy">Privacy information</Link></span></label>{error&&<p className="error-message" role="alert">{error}</p>}<Button type="submit" className="button purple" disabled={busy||!id}>{busy?<Loader2 className="spin"/>:<ArrowRight size={19}/>} {busy?'Saving your enquiry…':'Request my growth conversation'}</Button><p className="growth-form-footnote">Your enquiry is saved on submission. Scope and timing are agreed together.</p></fieldset></form></div>}