'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {CatIcon,TextLink} from './shared';
import {services} from '@/lib/content';
export function HomeServices(){const [selected,setSelected]=useState(services[0].slug);return <section id="cat-services" className="services-showcase section"><div className="container"><div className="section-heading"><div><h2>Local knowledge.<br/><em>Many superpowers.</em></h2></div><div className="service-heading-aside"><p>From your first impression to the next enquiry, give every part of your presence a purpose.</p><TextLink href="/services">Explore all services</TextLink></div></div><Tabs value={selected} onValueChange={setSelected} orientation="vertical" className="service-showcase-tabs"><TabsList className="service-directory" aria-label="Explore Viral Cat services">{services.map((s,i)=><TabsTrigger key={s.slug} value={s.slug}><span className="service-directory-number">0{i+1}</span><span><strong>{s.name}</strong><small>{s.cat}</small></span><ArrowUpRight size={21}/></TabsTrigger>)}</TabsList><div className="service-showcase-body">{services.map((s,i)=><TabsContent value={s.slug} key={s.slug} className="service-feature"><div className="service-feature-top"><span>{s.cat}</span><CatIcon name={s.icon} size={34}/></div><span className="service-feature-number" aria-hidden="true">0{i+1}</span><h3>{s.name}</h3><p>{s.description}</p><ul>{s.outputs.slice(0,4).map(item=><li key={item}><ArrowRight size={16}/>{item}</li>)}</ul><Button asChild className="button orange"><Link href={'/services/'+s.slug}>Explore {s.cat}<ArrowUpRight/></Link></Button></TabsContent>)}</div></Tabs><div className="services-bottom-note"><span>One neighbourhood. A connected approach.</span><Link href="/about#process">See how we work <ArrowUpRight size={17}/></Link></div></div></section>}
