'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Plus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
const journeys:Record<string,{kicker:string;title:string;intro:string;steps:[string,string,string][]}>={
food:{kicker:'THE LOCAL MENU / PICK A STORY',title:'There’s more on the menu than the food.',intro:'Three ways to make a café or restaurant feel familiar before someone arrives.',steps:[['The dish','Let the detail do the talking.','Choose one signature dish. Show an ingredient, a technique or the finishing touch that makes it yours.'],['The maker','Give the flavour a familiar face.','Let the person behind the dish explain one small detail in their own voice.'],['The ritual','Make the visit feel like a habit.','Show the morning pour, a lunch break or an evening catch-up. End with a clear invitation to visit.']]},
retail:{kicker:'THE SHOWROOM DESK / CHOOSE A CUSTOMER QUESTION',title:'Make the detail easier to imagine.',intro:'A good product story answers what a customer would ask while standing in your store.',steps:[['What is it like?','Show texture and detail.','Bring the product close. Explain the material and features using verified product information.'],['Will it fit?','Give it scale and context.','Show the product in a realistic setting. Include accurate dimensions when they help the decision.'],['How will I use it?','Demonstrate the everyday use.','Show the product doing its job. Let someone from the store answer a practical question.']]},
beauty:{kicker:'THE FIRST-VISIT WALKTHROUGH',title:'A little reassurance before the appointment.',intro:'Help someone understand the experience before asking them to book.',steps:[['A familiar hello','Introduce the person who welcomes them.','A team introduction gives a new customer a face and a name before the first visit.'],['A useful conversation','Explain how the consultation works.','Show how your team listens, discusses appropriate options and confirms the service.'],['A clear next step','Tell them how to ask about a visit.','Make the enquiry route easy to find. Confirm suitability and availability directly.']]},
fitness:{kicker:'THE BEGINNER’S POINT OF VIEW',title:'Start with the first ten minutes.',intro:'A sample content direction to help someone picture their first session.',steps:[['Before arrival','What should I bring?','Explain the practical essentials and who can answer questions before the session.'],['The welcome','Will I know what to do?','Introduce the trainer and the space. Show how a beginner is guided through the start.'],['The next step','Can I ask about trying it?','Invite a conversation about the session. Confirm availability and suitability with your team.']]}
};
export function IndustryExperience({id}:{id:string}){const [active,setActive]=useState(0),[town,setTown]=useState(''),[job,setJob]=useState('A repair or maintenance job');if(id==='education')return <section className="industry-experience industry-experience-education"><div className="container education-desk"><div><h2>A better conversation<br/>starts with <em>a better question.</em></h2><p>Choose a question. See the kind of information a useful course story should include.</p></div><Accordion type="single" collapsible defaultValue="0">{[['Is this course right for me?','Explain the intended learner, prerequisites and what the course covers. Use verified information rather than broad promises.'],['What will learning look like?','Introduce a faculty member, the format and the learning environment. Show a concrete example of how a topic is taught.'],['What should I do before applying?','Make the current intake information, eligibility requirements and enquiry route easy to find. Help people know what to ask next.']].map(([q,a],n)=><AccordionItem key={q} value={String(n)}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>;
if(id==='services')return <section className="industry-experience industry-experience-services"><div className="container service-job-desk"><div><h2>A clear question.<br/><em>A more useful response.</em></h2><p>See the kind of enquiry template your customer could use. This is a planning example for your marketing.</p><Label htmlFor="example-job">Example service need</Label><select id="example-job" value={job} onChange={e=>setJob(e.target.value)}><option>A repair or maintenance job</option><option>A new installation</option><option>A service appointment</option></select><Label htmlFor="example-town">Example customer location</Label><Input id="example-town" value={town} onChange={e=>setTown(e.target.value)} maxLength={100} placeholder="Town or neighbourhood"/></div><div className="job-message"><span>CUSTOMER ENQUIRY / EXAMPLE</span><h3>A little context<br/>helps a lot.</h3><p>I’d like help with <strong>{job.toLowerCase()}</strong> in <strong>{town.trim()||'my neighbourhood'}</strong>.</p><p>Here is what needs attention: [brief description]. My preferred timing is [date or timeframe]. Please let me know what details you need.</p><Link className="text-link" href={'/contact?industry=services&idea='+encodeURIComponent('Create a clear customer enquiry route for our local service business. Example need: '+job+'. Area: '+town)}>Build this into my marketing <ArrowUpRight size={18}/></Link></div></div></section>;
const j=journeys[id];if(!j)return null;return <section className={'industry-experience industry-experience-'+id}><div className="container"><div className="industry-experience-heading"><h2>{j.title}</h2><p>{j.intro}</p></div><div className={'industry-experience-board board-'+id}><div className="industry-experience-options" role="group" aria-label="Choose a customer story">{j.steps.map(([label],n)=><Button variant="ghost" key={label} aria-pressed={active===n} onClick={()=>setActive(n)}><span>0{n+1}</span><strong>{label}</strong><ArrowUpRight size={19}/></Button>)}</div><div className="industry-experience-result" aria-live="polite"><span className="industry-scene-number">0{active+1}</span><span className="experiment-label">{j.steps[active][0].toUpperCase()}</span><h3>{j.steps[active][1]}</h3><p>{j.steps[active][2]}</p><div><Link className="text-link" href={'/contact?industry='+id+'&idea='+encodeURIComponent(j.steps[active].join('. '))}>Explore this direction <ArrowUpRight size={18}/></Link><Button variant="ghost" size="icon" aria-label="Next story direction" onClick={()=>setActive((active+1)%j.steps.length)}><ArrowRight/></Button></div></div></div></div></section>}
