'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,Menu,Phone,Mail,PawPrint,Compass} from 'lucide-react';
import {NavigationMenu,NavigationMenuList,NavigationMenuItem,NavigationMenuTrigger,NavigationMenuContent,NavigationMenuLink} from '@/components/ui/navigation-menu';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetTrigger} from '@/components/ui/sheet';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Button} from '@/components/ui/button';
import {services,industries} from '@/lib/content';
import {contact} from '@/lib/contact';
import {CatIcon} from './shared';
const explorations=[{name:'Play Cat Street',href:'/play',description:'Five playful puzzles. A curious Cat.'},{name:'How we work',href:'/how-we-work',description:'From first brief to what comes next.'},{name:'Grow locally',href:'/local-growth',description:'Find a direction for your next campaign.'},{name:'Find my Cat',href:'/cat-lab',description:'Discover a useful starting point.'},{name:'Local presence check',href:'/cat-lab/check',description:'Six questions. Your next steps.'},{name:'The idea lab',href:'/cat-lab/ideas',description:'Find a little local inspiration.'},{name:'Local knowledge',href:'/learn',description:'Practical guides for your business.'},{name:'Our territory',href:'/areas',description:'Plan your customer catchment.'}];
export function MegaMenu(){const [open,setOpen]=useState('');const path=usePathname();useEffect(()=>setOpen(''),[path]);const close=()=>setOpen('');return <><NavigationMenu value={open} onValueChange={setOpen} viewport={false} delayDuration={100} className="mega-navigation" aria-label="Main navigation"><NavigationMenuList className="mega-list">
<NavigationMenuItem value="services"><NavigationMenuTrigger>Services</NavigationMenuTrigger><NavigationMenuContent className="mega-panel"><div className="mega-panel-main"><div className="mega-panel-title"><span>THE CAT FAMILY</span><NavigationMenuLink asChild onSelect={close}><Link href="/services">All services <ArrowUpRight size={16}/></Link></NavigationMenuLink></div><div className="mega-link-grid">{services.map(s=><NavigationMenuLink asChild onSelect={close} key={s.slug}><Link href={'/services/'+s.slug} className="mega-rich-link" aria-current={path==='/services/'+s.slug?'page':undefined}><span className="mega-icon"><CatIcon name={s.icon} size={23}/></span><span><strong>{s.name}</strong><small>{s.short}</small></span><ArrowUpRight size={16}/></Link></NavigationMenuLink>)}</div></div><aside className="mega-feature"><Compass size={29}/><span>CURIOUS WHERE TO START?</span><h3>Find your<br/>local advantage.</h3><p>A few details about your business. A useful way forward.</p><NavigationMenuLink asChild onSelect={close}><Link href="/cat-lab">Find my Cat <ArrowUpRight size={18}/></Link></NavigationMenuLink></aside></NavigationMenuContent></NavigationMenuItem>
<NavigationMenuItem value="business"><NavigationMenuTrigger>Your business</NavigationMenuTrigger><NavigationMenuContent className="mega-panel"><div className="mega-panel-main"><div className="mega-panel-title"><span>For your business</span><NavigationMenuLink asChild onSelect={close}><Link href="/your-business">Explore all <ArrowUpRight size={16}/></Link></NavigationMenuLink></div><div className="mega-link-grid">{industries.map(i=><NavigationMenuLink asChild key={i.id} onSelect={close}><Link className="mega-rich-link" href={'/your-business/'+i.id} aria-current={path==='/your-business/'+i.id?'page':undefined}><span className="mega-icon"><CatIcon name={i.icon}/></span><span><strong>{i.name}</strong><small>{i.focus}</small></span><ArrowUpRight size={16}/></Link></NavigationMenuLink>)}</div></div><aside className="mega-feature mega-feature-orange"><PawPrint size={30}/><h3>Every business<br/>has a story.</h3><p>Let’s find the one your neighbourhood will recognise.</p><NavigationMenuLink asChild onSelect={close}><Link href="/contact">Tell us yours <ArrowUpRight size={18}/></Link></NavigationMenuLink></aside></NavigationMenuContent></NavigationMenuItem>
<NavigationMenuItem><NavigationMenuLink asChild active={path.startsWith('/work')} onSelect={close}><Link className="mega-direct" href="/work">Our work</Link></NavigationMenuLink></NavigationMenuItem>
<NavigationMenuItem><NavigationMenuLink asChild active={path==='/about'} onSelect={close}><Link className="mega-direct" href="/about">About us</Link></NavigationMenuLink></NavigationMenuItem>
<NavigationMenuItem value="explore"><NavigationMenuTrigger>Explore</NavigationMenuTrigger><NavigationMenuContent className="mega-panel"><div className="mega-panel-main"><div className="mega-panel-title"><span>FOLLOW YOUR CURIOSITY</span><NavigationMenuLink asChild onSelect={close}><Link href="/about">Meet Viral Cat <ArrowUpRight size={16}/></Link></NavigationMenuLink></div><div className="mega-link-grid">{explorations.map((e,i)=><NavigationMenuLink asChild key={e.href} onSelect={close}><Link href={e.href} aria-current={path===e.href?'page':undefined} className="mega-rich-link"><span className="mega-number">{String(i+1).padStart(2,'0')}</span><span><strong>{e.name}</strong><small>{e.description}</small></span><ArrowUpRight size={16}/></Link></NavigationMenuLink>)}</div></div><aside className="mega-feature"><span>LET’S SAY HELLO</span><h3>A good chat.<br/>A fresh start.</h3><a className="mega-contact-link" href={contact.phoneHref}><Phone size={17}/>{contact.phone}</a><a className="mega-contact-link" href={contact.emailHref}><Mail size={17}/>{contact.email}</a><NavigationMenuLink asChild onSelect={close}><Link href="/contact">Start a conversation <ArrowUpRight size={18}/></Link></NavigationMenuLink></aside></NavigationMenuContent></NavigationMenuItem>
</NavigationMenuList></NavigationMenu>{open&&<button tabIndex={-1} className="mega-scrim" aria-label="Close navigation menu" onClick={close}/>}</>}
export function MobileNavigation(){const [open,setOpen]=useState(false);const path=usePathname();useEffect(()=>setOpen(false),[path]);const close=()=>setOpen(false);return <Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="mobile-menu" aria-label="Open navigation"><Menu/></Button></SheetTrigger><SheetContent className="mobile-mega-sheet"><SheetTitle>Good to see you.</SheetTitle><SheetDescription>Follow a little curiosity.</SheetDescription><nav aria-label="Mobile navigation"><Accordion type="multiple" className="mobile-mega-groups"><AccordionItem value="services"><AccordionTrigger>Our services</AccordionTrigger><AccordionContent><Link href="/services" onClick={close}>Explore all services <ArrowUpRight size={17}/></Link>{services.map(s=><Link href={'/services/'+s.slug} key={s.slug} onClick={close}><CatIcon name={s.icon} size={19}/><span>{s.name}<small>{s.cat}</small></span><ArrowUpRight size={15}/></Link>)}</AccordionContent></AccordionItem><AccordionItem value="business"><AccordionTrigger>Your business</AccordionTrigger><AccordionContent><Link href="/your-business" onClick={close}>Explore all businesses <ArrowUpRight size={17}/></Link>{industries.map(i=><Link href={'/your-business/'+i.id} key={i.id} onClick={close}><CatIcon name={i.icon} size={19}/><span>{i.name}</span><ArrowUpRight size={15}/></Link>)}</AccordionContent></AccordionItem><AccordionItem value="explore"><AccordionTrigger>Explore & try</AccordionTrigger><AccordionContent>{explorations.map(e=><Link href={e.href} key={e.href} onClick={close}><span>{e.name}</span><ArrowUpRight size={15}/></Link>)}</AccordionContent></AccordionItem></Accordion><div className="mobile-direct-links">{[['Our work','/work'],['About Viral Cat','/about'],['How we work','/how-we-work'],['Contact us','/contact']].map(([n,h])=><Link href={h} key={h} onClick={close}>{n}<ArrowUpRight size={18}/></Link>)}</div></nav><div className="mobile-menu-contact"><a href={contact.phoneHref}><Phone size={18}/>{contact.phone}</a><a href={contact.emailHref}><Mail size={18}/>{contact.email}</a></div></SheetContent></Sheet>}
