'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Check,Plus,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {CatIcon} from '@/components/shared';
import {services} from '@/lib/content';
export function ServiceExplorer(){const [selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState(false);function toggle(slug:string){setSelected(s=>s.includes(slug)?s.filter(x=>x!==slug):s.length<3?[...s,slug]:s)}return <><div className="explorer-note"><p>Start with what your business needs. Select up to three services to compare.</p><Link className="text-link" href="/cat-lab">Help me choose <ArrowUpRight size={17}/></Link></div><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.slug}><div className="service-top"><span className="icon-tile"><CatIcon name={s.icon}/></span><span className="tiny-number">0{i+1}</span></div><h3>{s.name}</h3><p>{s.description}</p><div className="service-card-actions"><Link href={'/services/'+s.slug} className="text-link">Explore service <ArrowUpRight size={17}/></Link><Button variant="outline" size="sm" onClick={()=>toggle(s.slug)} disabled={selected.length===3&&!selected.includes(s.slug)} aria-pressed={selected.includes(s.slug)}>{selected.includes(s.slug)?<Check size={14}/>:<Plus size={14}/>} Compare</Button></div></article>)}</div>{selected.length>0&&<div className="compare-bar"><span><strong>{selected.length}</strong> of 3 selected</span><Button variant="ghost" onClick={()=>setSelected([])}>Clear</Button><Button className="button purple" onClick={()=>setCompare(true)}>Compare services <ArrowUpRight size={17}/></Button></div>}<Dialog open={compare} onOpenChange={setCompare}><DialogContent className="compare-dialog"><DialogTitle>Find your starting point.</DialogTitle><DialogDescription>Different roles. One connected local presence.</DialogDescription><div className="comparison-scroll"><table className="compare-table"><thead><tr><th>What to consider</th>{selected.map(slug=><th key={slug}>{services.find(s=>s.slug===slug)?.name}</th>)}</tr></thead><tbody>{[['Purpose','description'],['What we need','input'],['How we review','measure']].map(([label,key])=><tr key={key}><th>{label}</th>{selected.map(slug=><td key={slug}>{services.find(s=>s.slug===slug)?.[key as 'description'|'input'|'measure']}</td>)}</tr>)}</tbody></table></div><Button asChild className="button purple"><Link href={'/contact?services='+selected.join(',')} onClick={()=>setCompare(false)}>Add these to my brief <ArrowUpRight/></Link></Button></DialogContent></Dialog></>}
