'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,PawPrint,Plus,MessageCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {faqs} from '@/lib/content';
import {contact} from '@/lib/contact';
import {MegaMenu,MobileNavigation} from './mega-menu';
import {SiteMotion} from './site-motion';
export function SiteShell({children}:{children:React.ReactNode}){
const campaign=usePathname()==='/local-growth';
const [ask,setAsk]=useState(false),[question,setQuestion]=useState(-1),[motion,setMotion]=useState(false);
useEffect(()=>{let saved=false;try{saved=localStorage.getItem('vc-reduce-motion')==='1'}catch{}document.documentElement.dataset.reducedMotion=String(saved);const sync=()=>setMotion(document.documentElement.dataset.reducedMotion==='true');sync();const observer=new MutationObserver(sync);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-reduced-motion']});return()=>observer.disconnect()},[]);
if(campaign)return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header campaign-header"><div className="header-inner"><Link href="/" aria-label="Viral Cat home" className="brand-logo"><img src="/assets/viral-cat-logo.png" alt="Viral Cat, a chapter of Mindstory" width="1200" height="644"/></Link><a href={contact.phoneHref} className="campaign-header-phone">{contact.phone}</a><Button asChild className="button purple"><a href="#growth-enquiry">Let’s talk <ArrowUpRight size={18}/></a></Button></div></header><main id="main">{children}</main><SiteMotion/><footer className="campaign-footer container"><Link href="/">Viral Cat · A chapter of Mindstory</Link><a href={contact.emailHref}>{contact.email}</a><Link href="/privacy">Privacy</Link></footer></>;
return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><Link href="/" aria-label="Viral Cat home" className="brand-logo"><img src="/assets/viral-cat-logo.png" alt="Viral Cat, a chapter of Mindstory" width="1200" height="644"/></Link><MegaMenu/><div className="header-actions"><Button asChild className="button purple header-cta"><Link href="/contact">Let’s talk <ArrowUpRight/></Link></Button><MobileNavigation/></div></div></header><main id="main">{children}</main><SiteMotion/><footer className="site-footer"><div className="container footer-top"><div><h2>Tell us about<br/><em>your business.</em></h2><Button asChild className="button orange"><Link href="/contact">Start a conversation <ArrowUpRight/></Link></Button></div><div className="footer-links"><div><span>Explore</span><Link href="/services">Our services</Link><Link href="/your-business">Your business</Link><Link href="/work">Our work</Link><Link href="/about">Meet Viral Cat</Link><Link href="/how-we-work">How we work</Link><Link href="/contact">Contact us</Link></div><div><span>Helpful tools</span><Link href="/cat-lab">Find my Cat</Link><Link href="/cat-lab/check">Local presence check</Link><Link href="/learn">Local knowledge</Link><Link href="/areas">Areas we serve</Link><Link href="/play">Play Cat Street</Link><Link href="/local-growth">Grow locally</Link></div></div></div><div className="container footer-contact-strip"><span>Say hello</span><a href={contact.phoneHref}>{contact.phone}</a><a href={contact.telephoneHref}>{contact.telephone}</a><a href={contact.emailHref}>{contact.email}</a></div><div className="container footer-bottom"><Link href="/" className="footer-wordmark">viral cat<span>.</span></Link><p>A chapter of <strong>MINDSTORY</strong></p><div><Link href="/privacy">Privacy</Link><button onClick={()=>{const n=!motion;setMotion(n);try{localStorage.setItem('vc-reduce-motion',n?'1':'0')}catch{};document.documentElement.dataset.reducedMotion=String(n)}}>{motion?'Motion reduced':'Reduce motion'}</button></div><span>© {new Date().getFullYear()} Viral Cat</span></div></footer><Button className="ask-cat" onClick={()=>setAsk(true)} aria-label="Ask Cat about Viral Cat"><MessageCircle size={19}/><span>Ask Cat</span></Button><Dialog open={ask} onOpenChange={setAsk}><DialogContent className="cat-dialog"><div className="icon-tile"><PawPrint/></div><DialogTitle>Curious? You’re in the right place.</DialogTitle><DialogDescription>Choose a question about Viral Cat.</DialogDescription><div className="ask-options">{faqs.slice(0,5).map(([q,a],i)=><div key={q}><Button variant="outline" onClick={()=>setQuestion(question===i?-1:i)} aria-expanded={question===i}>{q}<Plus size={16}/></Button>{question===i&&<p>{a}</p>}</div>)}</div><Button asChild className="button purple"><Link href="/contact" onClick={()=>setAsk(false)}>Talk about my business <ArrowRight/></Link></Button></DialogContent></Dialog></>}
