import Link from 'next/link';
import {ArrowUpRight,Compass,Camera,MessageCircle,ClipboardCheck,ChartNoAxesCombined} from 'lucide-react';
import {Button} from '@/components/ui/button';
export const processSteps=[
 {title:'Listen closely.',description:'Your business, your customers and the neighbourhood you can serve. We begin with the details only you know.',output:'A clear business brief',icon:Compass},
 {title:'Find the direction.',description:'Agree the audience, message, channels and next customer action. Give each piece of work a reason to exist.',output:'An agreed creative direction',icon:MessageCircle},
 {title:'Make it feel like you.',description:'Turn the direction into stories, useful content and campaigns grounded in your actual people, products and place.',output:'Drafts ready for review',icon:Camera},
 {title:'Review, then share.',description:'Check the message and business facts together. Confirm the final version and publishing arrangements before it goes out.',output:'Approved content and next steps',icon:ClipboardCheck},
 {title:'Learn from the response.',description:'Review available activity and the questions your team receives. Use confirmed customer feedback to shape the next round.',output:'A practical next-action list',icon:ChartNoAxesCombined}
];
export function AboutHome(){return <section className="about-home section container" id="about-us"><div><h2>Big ideas.<br/>Neighbourhood<br/><em>instincts.</em></h2></div><div className="about-home-copy"><p>Behind every local business is something worth knowing. The person who opens up early. The product made with care. The familiar welcome.</p><p>We help those details become stories people nearby can recognise, remember and act on. Strategy, content and digital marketing, brought closer to home.</p><Button asChild className="button purple"><Link href="/about">Get to know the Cat <ArrowUpRight/></Link></Button><div className="about-home-principles"><span>Curious by nature.</span><span>Local by design.</span><span>Clear in our approach.</span></div></div></section>}
export function ProcessSection({full=false}:{full?:boolean}){return <section className="section container process-editorial" id="process"><div className="section-heading"><div><h2>Good work starts<br/><em>with a good process.</em></h2></div>{!full&&<Link className="text-link" href="/how-we-work">How we work <ArrowUpRight size={18}/></Link>}</div><div className="process-editorial-list">{processSteps.map((s,i)=><article key={s.title}><span className="process-number">0{i+1}</span><s.icon size={25}/><h3>{s.title}</h3><p>{s.description}</p><span className="process-output">{s.output}</span></article>)}</div></section>}
