import type {Point} from './cat-walk-world';
export type Neighbour={id:string;name:string;role:string;color:string;topic:string;message:string;takeaway:string;route:Point[]};
export const neighbours:Neighbour[]=[
 {id:'mira',name:'Mira',role:'Your local guide',color:'#8ad9c6',topic:'Help people find the door.',message:'I used to follow map pins that led to the back of the shop! A correct entrance pin and a recent street photo make the first visit much easier.',takeaway:'Try this: check your business pin from the pavement.',route:[{x:-6,z:21.5},{x:-4.8,z:24.5},{x:-4.8,z:26}]},
 {id:'ari',name:'Ari',role:'The neighbourhood baker',color:'#ffbb68',topic:'Let people into your story.',message:'The morning baking makes a better story than another “buy now” post. Show how you make something, answer a customer question, then tell people where to find it.',takeaway:'Try this: film one real moment behind the scenes.',route:[{x:-10,z:12.4},{x:-6,z:12.4}]},
 {id:'noor',name:'Noor',role:'Creator around the corner',color:'#d4aeff',topic:'Right people. Right moment.',message:'The lunch crowd and evening shoppers are different audiences. Start with the streets your customers actually travel from, then choose a time when they can act.',takeaway:'Try this: describe one nearby customer and their daily routine.',route:[{x:-26,z:-19.55},{x:-22,z:-19.55}]},
 {id:'dev',name:'Dev',role:'Your friendly shopkeeper',color:'#ff9c9a',topic:'Be the business that replies.',message:'A useful reply can turn a question into a visit. I check availability, answer clearly, and invite real customers to share honest feedback after their visit.',takeaway:'Try this: make your most common customer answer easy to find.',route:[{x:6,z:-19.55},{x:10,z:-19.55}]},
 {id:'zoe',name:'Zoe',role:'The numbers neighbour',color:'#bbdf79',topic:'Count what actually helps.',message:'Lots of likes feels good. But did people call, book or walk in? Track those separately and ask visitors how they found you. That helps you decide what to improve.',takeaway:'Try this: record enquiries and confirmed visits this week.',route:[{x:5.6,z:22},{x:8.5,z:21.5},{x:12,z:21.5},{x:12,z:22.4}]}
];
