export const stages=[
  {name:'Open the doors',short:'Get found',title:'Give your café a place on the map.',instruction:'You have room for 3 essentials. Tap the signs that help a nearby customer visit today.',lesson:'Accurate location, current hours and a clear contact route remove friction between discovery and a visit. A listing still needs verification and regular updates.',service:'local-discovery',result:'Your café is easier to find.',options:[{id:'pin',label:'Accurate map pin',detail:'A route to the right doorstep',good:true},{id:'hours',label:'Today’s opening hours',detail:'No wasted trips',good:true},{id:'followers',label:'A giant follower count',detail:'A big number on the wall',good:false},{id:'contact',label:'Call / message button',detail:'A way to ask before visiting',good:true},{id:'slogan',label:'“Best café in the universe”',detail:'A very loud claim',good:false}],answer:['pin','hours','contact']},
  {name:'Make a little story',short:'Create',title:'Build a post worth stopping for.',instruction:'Tap the 3 story cards in the order you would publish them: catch attention, show something real, then help people act.',lesson:'A local hook earns attention, real proof builds confidence, and a clear invitation makes the next step easy. Reach alone does not guarantee customers.',service:'content-production',result:'A useful story is ready to share.',options:[{id:'visit',label:'“Opposite the park. Drop by before 6.”',detail:'The invitation',good:true},{id:'proof',label:'A close-up of today’s fresh bake',detail:'The real product',good:true},{id:'hook',label:'“Your 4 pm break, two streets away.”',detail:'A reason to pause',good:true}],answer:['hook','proof','visit']},
  {name:'Meet the neighbourhood',short:'Reach nearby',title:'Spend your 3 promotion tokens wisely.',instruction:'Tap 3 places on the neighbourhood board. Your café serves walk-in customers; choose people likely to visit.',lesson:'Hyperlocal marketing connects relevance with distance. A nearby audience and a suitable offer can be more useful than a huge audience that cannot visit. Test the real catchment; distance alone is not intent.',service:'local-campaigns',result:'Your message has a more useful audience.',options:[{id:'office',label:'Office lunch crowd',detail:'400 m • weekday breaks',good:true},{id:'world',label:'Worldwide trend feed',detail:'Millions of distant viewers',good:false},{id:'homes',label:'Nearby residents',detail:'700 m • evening walks',good:true},{id:'commuters',label:'Local station commuters',detail:'900 m • coffee on the way',good:true},{id:'city',label:'Another city’s fan club',detail:'120 km • unlikely to drop in',good:false}],answer:['office','homes','commuters']},
  {name:'Turn a hello into a visit',short:'Reply well',title:'The neighbourhood is messaging you.',instruction:'Choose a helpful reply for each customer. No countdown: good conversations deserve a little attention.',lesson:'Useful, specific replies help people decide. Share accurate details, avoid promises you cannot keep, and ask for permission before following up.',service:'social-media',result:'Three customers have a clearer next step.',options:[{id:'directions',label:'Share the map link and nearby landmark',detail:'Make the route clear',good:true},{id:'menu',label:'Share today’s options and confirm ingredients',detail:'Help them choose safely',good:true},{id:'reserve',label:'Check availability, then confirm the time',detail:'Only promise what you can deliver',good:true},{id:'generic',label:'“Hi! Follow us and tell all your friends.”',detail:'A reply that misses the question',good:false}],answer:['directions','menu','reserve']},
  {name:'Read the real signals',short:'Learn & grow',title:'What actually moved the business?',instruction:'Sort the 4 receipts into attention, enquiry or confirmed outcome. Tap a receipt, then its tray.',lesson:'Views show attention; messages show interest; verified visits or orders show outcomes. Track them separately. These game results are fictional, and real attribution requires reliable measurement.',service:'local-strategy',result:'You’re thinking like a local marketer.',options:[{id:'views',label:'1,200 reel views',detail:'People saw the post',good:true},{id:'question',label:'“Are you open this evening?”',detail:'A customer sends a message',good:true},{id:'visit',label:'A recorded in-store purchase',detail:'A completed purchase',good:true},{id:'likes',label:'85 likes on the café post',detail:'A reaction to the content',good:true}],answer:['attention','enquiry','outcome','attention']},
] as const;
export const customerQuestions=['“How do I find you from the park?”','“Do you have an egg-free option today?”','“Can I book a table for 5 pm?”'];
export const receiptTrays=[{id:'attention',name:'Attention',detail:'They noticed us'},{id:'enquiry',name:'Enquiry',detail:'They asked us'},{id:'outcome',name:'Confirmed outcome',detail:'They bought or visited'}];
export function gradeStage(stage:number,actions:unknown):{score:number;passed:boolean;correct:boolean[]}{
  if(!Number.isInteger(stage)||stage<0||stage>=stages.length||!Array.isArray(actions))throw new Error('Choose a valid stage.');
  const s=stages[stage];const expected=stage===4?4:3;
  if(actions.length!==expected||actions.some(x=>typeof x!=='string'))throw new Error('Finish each choice before checking your move.');
  const allowed:readonly string[]=stage===4?receiptTrays.map(x=>x.id):s.options.map(x=>x.id);
  if(actions.some(x=>!allowed.includes(x))||(stage!==3&&stage!==4&&new Set(actions).size!==actions.length))throw new Error('Use the choices shown in this stage.');
  const answers:readonly string[]=s.answer;
  const correct=actions.map((x,i)=>stage===0||stage===2?answers.includes(x):x===answers[i]);
  const score=Math.round(correct.filter(Boolean).length/expected*200);
  return {score,passed:score>=133,correct};
}
export type StreetProgress={scores:number[];unlocked:number;revision:number};
export const emptyProgress:StreetProgress={scores:[0,0,0,0,0],unlocked:0,revision:0};
export function totalPoints(p:StreetProgress){return p.scores.reduce((a,b)=>a+b,0)}
export function rewardCap(points:number){return points>=1000?100000:points>=600?50000:0}
export function money(paise:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(paise/100)}
// All financial values are integer paise. Keep >=40% gross margin on the net eligible fee.
export function discountFor(points:number,fee:number,cost:number){
  if(!Number.isSafeInteger(fee)||!Number.isSafeInteger(cost)||fee<1000000||fee>1000000000||cost<0||cost>fee)throw new Error('Enter eligible fees of at least ₹10,000 and complete direct delivery costs.');
  return Math.max(0,Math.min(rewardCap(points),Math.floor(fee/20),fee-Math.ceil(cost*5/3)));
}
