import * as T from 'three';
import {createOriginalCatSprite} from './original-cat-sprite';
import {puzzles,goals,floor,sameCell,type Cell,type PuzzleState} from './cat-puzzles';
export type PuzzleScene={show:(stage:number,state:PuzzleState)=>void;hint:(cell:Cell|null)=>void;celebrate:()=>void;dispose:()=>void};
export async function createPuzzleScene(host:HTMLElement,onCell:(cell:Cell)=>void):Promise<PuzzleScene>{
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const canvas=renderer.domElement;canvas.className='puzzle-canvas';canvas.setAttribute('aria-hidden','true');host.appendChild(canvas);
 const scene=new T.Scene();scene.background=new T.Color(0xe7e1f0);scene.add(new T.HemisphereLight(0xfff8e9,0x887694,2.7));const sun=new T.DirectionalLight(0xffedcf,2.5);sun.position.set(-6,12,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,far:40});sun.shadow.normalBias=.04;scene.add(sun);
 const camera=new T.OrthographicCamera(-8,8,6,-6,.1,60);camera.position.set(0,13,9);camera.lookAt(0,0,0);
 let cat:Awaited<ReturnType<typeof createOriginalCatSprite>>;try{cat=await createOriginalCatSprite()}catch(error){renderer.dispose();canvas.remove();throw error}cat.root.scale.setScalar(.43);cat.root.children[2].visible=false;scene.add(cat.root);
 const mats=new Map<number,T.MeshStandardMaterial>();const mat=(color:number)=>{if(!mats.has(color))mats.set(color,new T.MeshStandardMaterial({color,roughness:.85}));return mats.get(color)!};
 const cube=new T.BoxGeometry(1,1,1),sphere=new T.SphereGeometry(1,14,10);const textures:T.Texture[]=[];
 let board=new T.Group();scene.add(board);let stage=-1,state:PuzzleState,crates:T.Group[]=[],goalMeshes:T.Mesh[]=[],active=true,last=0,clock=0,confettiTime=2;
 const tile=1.2,catTarget=new T.Vector3();
 function position(cell:Cell){return new T.Vector3((cell.x-(puzzles[stage].map[0].length-1)/2)*tile,.14,(cell.y-(puzzles[stage].map.length-1)/2)*tile)}
 function box(x:number,y:number,z:number,w:number,h:number,d:number,color:number,parent:T.Object3D=board){const m=new T.Mesh(cube,mat(color));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function ball(x:number,y:number,z:number,r:number,color:number){const m=new T.Mesh(sphere,mat(color));m.position.set(x,y,z);m.scale.setScalar(r);m.castShadow=true;board.add(m);return m}
 function parcelLabel(text:string){const c=document.createElement('canvas');c.width=256;c.height=128;const g=c.getContext('2d')!;g.fillStyle='#fff0d8';g.fillRect(0,0,256,128);g.fillStyle='#854087';g.font='bold 52px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(text,128,66,230);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;textures.push(t);return new T.MeshBasicMaterial({map:t,toneMapped:false})}
 const hint=new T.Mesh(new T.RingGeometry(.38,.46,32),new T.MeshBasicMaterial({color:0x84439b,side:T.DoubleSide,transparent:true,opacity:.9,depthWrite:false}));hint.rotation.x=-Math.PI/2;hint.visible=false;scene.add(hint);
 const confetti=Array.from({length:30},(_,i)=>{const m=new T.Mesh(cube,mat([0xffab39,0xbc8ad6,0x8cd6b9,0xf4a3b4][i%4]));m.scale.setScalar(0);scene.add(m);return m});
 function clearBoard(){const gs=new Set<T.BufferGeometry>(),ms=new Set<T.Material>();board.traverse(o=>{const m=o as T.Mesh;if(m.geometry&&m.geometry!==cube&&m.geometry!==sphere)gs.add(m.geometry);if(m.material&&!Array.isArray(m.material)&&![...mats.values()].includes(m.material as T.MeshStandardMaterial))ms.add(m.material)});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());textures.splice(0).forEach(t=>t.dispose());scene.remove(board);board=new T.Group();scene.add(board)}
 function show(nextStage:number,nextState:PuzzleState){const rebuilding=nextStage!==stage;if(rebuilding){clearBoard();stage=nextStage;crates=[];goalMeshes=[];const p=puzzles[stage],w=p.map[0].length,h=p.map.length;
   box(0,-.42,0,w*tile+.35,.55,h*tile+.35,0x9973b1);box(0,-.1,0,w*tile+.35,.16,h*tile+.35,0xfff5df);
   p.map.forEach((row,y)=>[...row].forEach((c,x)=>{const v=position({x,y});if(c==='#'){box(v.x,.24,v.z,1.14,.5,1.14,0xb6cda8);if((x+y)%3===0){ball(v.x,.57,v.z,.30,0x8cb690);ball(v.x+.15,.69,v.z-.05,.20,0xb1d1a0)}}else{const t=box(v.x,.03,v.z,1.15,.15,1.15,(x+y)%2?0xffecd4:0xfff5e4);t.userData.cell={x,y};}}));
   goals(stage).forEach(g=>{const v=position(g);const ring=new T.Mesh(new T.TorusGeometry(.40,.07,8,40),mat(0xb280c8));ring.rotation.x=-Math.PI/2;ring.position.copy(v);ring.position.y=.15;board.add(ring);goalMeshes.push(ring);const dot=new T.Mesh(new T.CircleGeometry(.23,32),new T.MeshBasicMaterial({color:0xd2b3df,side:T.DoubleSide}));dot.rotation.x=-Math.PI/2;dot.position.copy(v);dot.position.y=.13;board.add(dot)});
   const stamp=parcelLabel(p.parcel);nextState.crates.forEach(()=>{const g=new T.Group();board.add(g);box(0,.42,0,.78,.68,.78,0xf3ac54,g);box(0,.76,0,.8,.04,.8,0xffc97a,g);box(0,.43,.4,.16,.68,.018,0xffd79b,g);const label=new T.Mesh(new T.PlaneGeometry(.57,.28),stamp);label.position.set(0,.8,0);label.rotation.x=-Math.PI/2;g.add(label);const front=label.clone();front.rotation.x=0;front.position.set(0,.47,.411);g.add(front);crates.push(g)});
   cat.root.position.copy(position(nextState.cat));crates.forEach((g,i)=>g.position.copy(position(nextState.crates[i])).setY(.025));resize();
  }
  state=nextState;catTarget.copy(position(state.cat));goalMeshes.forEach((g,i)=>{const filled=state.crates.some(c=>sameCell(c,goals(stage)[i]));g.material=mat(filled?0x6fbca0:0xb280c8)});hint.visible=false;
 }
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);const p=puzzles[Math.max(0,stage)],aspect=w/h,half=Math.max((p.map[0].length*tile/2+.7)/aspect,p.map.length*tile*.81/2+.9);camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix()}
 const observer=new ResizeObserver(resize);observer.observe(host);
 const ray=new T.Raycaster();let down={x:0,y:0};const pointerDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY}};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>15||stage<0)return;const rect=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),camera);const ground=new T.Plane(new T.Vector3(0,1,0),-.12),hit=new T.Vector3();if(ray.ray.intersectPlane(ground,hit)){const p=puzzles[stage],cell={x:Math.round(hit.x/tile+(p.map[0].length-1)/2),y:Math.round(hit.z/tile+(p.map.length-1)/2)};if(floor(stage,cell))onCell(cell)}};
 canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointerup',pointerUp);
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.reducedMotion==='true';
 function render(ms:number){if(!active)return;const dt=Math.min(.035,last?(ms-last)/1000:.016);last=ms;clock+=dt;if(state){const distance=cat.root.position.distanceTo(catTarget),ease=reduced()?1:1-Math.exp(-dt*17);cat.root.position.lerp(catTarget,ease);cat.update(dt,distance>.02?4:0,0,Math.PI,reduced());crates.forEach((g,i)=>g.position.lerp(position(state.crates[i]).setY(.025),ease));hint.scale.setScalar(reduced()?1:1+Math.sin(clock*5)*.05)}
  confettiTime+=dt;confetti.forEach((m,i)=>{if(confettiTime<1.5&&!reduced()){const t=confettiTime,a=i*2.4;m.position.set(catTarget.x+Math.cos(a)*t*2,1.5+3*t-3*t*t,catTarget.z+Math.sin(a)*t*2);m.scale.set(.10*(1-t/1.5),.17*(1-t/1.5),.04);m.rotation.set(t*3,a,t*2)}else m.scale.setScalar(0)});renderer.render(scene,camera)}
 function visibility(){if(document.hidden)renderer.setAnimationLoop(null);else{last=0;renderer.setAnimationLoop(render)}}document.addEventListener('visibilitychange',visibility);renderer.setAnimationLoop(render);
 return {show,hint(cell){hint.visible=!!cell;if(cell){hint.position.copy(position(cell));hint.position.y=.18}},celebrate(){confettiTime=0},dispose(){active=false;renderer.setAnimationLoop(null);observer.disconnect();document.removeEventListener('visibilitychange',visibility);canvas.removeEventListener('pointerdown',pointerDown);canvas.removeEventListener('pointerup',pointerUp);clearBoard();const geometries=new Set<T.BufferGeometry>([cube,sphere]),materials=new Set<T.Material>(mats.values());scene.traverse(o=>{const m=o as T.Mesh;if(m.geometry)geometries.add(m.geometry);if(Array.isArray(m.material))m.material.forEach(a=>materials.add(a));else if(m.material)materials.add(m.material)});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());cat.dispose();sun.shadow.dispose();renderer.dispose();canvas.remove()}};
}
