export const catChapters = [
  { label: 'Get noticed', word: 'Hello.', title: 'A familiar face starts somewhere.', text: 'Show up where nearby people look. A clear business profile and a good local story make the first introduction.', shortText: 'A clear profile and a good local story help nearby people discover your business.', cat: 'Cat Radar', service: 'local-discovery', icon: 'radar', tag: 'FOUND AROUND HERE' },
  { label: 'Build trust', word: 'Curious?', title: 'Give them a reason to stay.', text: 'Your people. Your products. The details that make your business yours. Let the neighbourhood get to know the real story.', shortText: 'Show your people, your products and the details that make your business yours.', cat: 'Cat Personality', service: 'content-production', icon: 'personality', tag: 'REAL STORIES. REAL PEOPLE.' },
  { label: 'Start a conversation', word: 'Let’s talk.', title: 'Turn a little curiosity into a hello.', text: 'A useful message and a clear next step help interested people ask a question, plan a visit or start a conversation.', shortText: 'Give interested people a clear way to enquire, plan a visit or start a conversation.', cat: 'Cat Signal', service: 'local-campaigns', icon: 'signal', tag: 'ONE CLEAR NEXT STEP' },
  { label: 'Keep learning', word: 'What’s next?', title: 'Every response tells you something.', text: 'Look at the work, listen to your team and learn from actual customer conversations. Make the next local story a little better.', shortText: 'Listen to real customer conversations and make the next local story a little better.', cat: 'Cat Tracks', service: '', icon: 'territory', tag: 'LISTEN. LEARN. REPEAT.' },
];
export const clamp = (value:number, min=0, max=1) => Math.min(max, Math.max(min,value));
export function catScrollPose(progress:number){const p=clamp(progress);return {x:Math.sin(p*Math.PI*2)*27,y:Math.cos(p*Math.PI*2)*15-8,rotateY:Math.sin(p*Math.PI*2)*17,rotateZ:Math.sin(p*Math.PI*2+.5)*5,rotateX:5-Math.sin(p*Math.PI)*10,scale:.94+Math.sin(p*Math.PI)*.13,chapter:Math.min(3,Math.floor(p*4))}}
export const localStories:Record<string,{business:string;generic:string;local:string;detail:string;invitation:string}> = {
  food:{business:'THE CORNER CAFÉ',generic:'Great food.\nGreat offers.',local:'Your lunch break.\nOur favourite table.',detail:'Show a real dish being prepared, the people making it and the experience of dropping in.',invitation:'Pop in for your next lunch break.'},
  retail:{business:'THE NEIGHBOURHOOD STORE',generic:'New arrivals.\nShop now.',local:'See it. Try it.\nFind your favourite.',detail:'Show a new arrival in use and answer the question customers ask when they walk through the door.',invitation:'Come take a closer look.'},
  fitness:{business:'YOUR LOCAL STUDIO',generic:'Get fit.\nJoin today.',local:'First session?\nYou’ll fit right in.',detail:'Introduce a real trainer and show what a beginner can expect in their first session.',invitation:'Ask us about trying a session.'},
};
const remixHooks:Record<string,Record<string,string>>={
  food:{friendly:'Your next favourite might be just around the corner.',playful:'Good food. Short journey. Excellent decision.',clear:'Discover what’s cooking nearby.'},
  retail:{friendly:'Something you’ll love, closer than you think.',playful:'A little browse could become a very good idea.',clear:'Explore our products in person.'},
  beauty:{friendly:'A little time for you, right here in your neighbourhood.',playful:'Your next little glow-up has a local address.',clear:'Get to know our team and services.'},
  fitness:{friendly:'Your first step feels easier with a friendly face.',playful:'New here? Perfect. Everyone starts somewhere.',clear:'See what a session with us looks like.'},
  education:{friendly:'A question today could become your next chapter.',playful:'Big curiosity. A good place to start.',clear:'Explore our courses and learning environment.'},
  services:{friendly:'A local name for the help you need.',playful:'That job on your list? Let’s talk about it.',clear:'Find out how we can help.'},
};
export function buildLocalCaption({industry,tone,business,location,detail,action}:{industry:string;tone:string;business:string;location:string;detail:string;action:string}){const hooks=remixHooks[industry]||remixHooks.food;const hook=hooks[tone]||hooks.friendly;const name=business.trim()||'Your business';const place=location.trim();const introduction=place?`${name}, right here in ${place}.`:`Meet ${name}.`;const invitations:Record<string,string>={visit:'Drop in and say hello.',enquire:'Send us a message. We’d love to answer your questions.',appointment:'Ask us about your next appointment.'};return [hook,introduction,detail.trim(),invitations[action]||invitations.visit].filter(Boolean).join('\n\n')}
