export const services=[
{slug:'local-strategy',cat:'Cat Territory',name:'Local strategy',short:'Know your neighbourhood.',icon:'territory',description:'Good local marketing starts with the people around your business. We find the audience, priorities and stories that make sense for you.',outputs:['Customer catchment and audience review','Local competitor and opportunity review','Business positioning and key messages','A focused content and campaign direction'],input:'Your location, main services, customer questions and current business priorities.',measure:'A clear agreed direction, audience focus and practical priorities for the work.',example:'A new café could focus on nearby office-goers for weekday lunches and families for weekends.'},
{slug:'content-production',cat:'Cat Personality',name:'Content production',short:'Give them something to notice.',icon:'personality',description:'Your products, your people, your everyday magic. We turn the things that make your business special into stories worth stopping for.',outputs:['Short videos and reels','On-location business and product shoots','Team introductions and service explainers','Genuine customer stories with consent'],input:'Access to your space, available products, team members and approved customer participants.',measure:'Content delivered, reach, viewing and interactions, alongside feedback from your team.',example:'A signature dish, the chef behind it and the reason people come back. One real story with a local point of view.'},
{slug:'social-media',cat:'Cat Voice',name:'Social media',short:'Sound like a familiar face.',icon:'voice',description:'A social presence that feels like your business. Thoughtful posts, local language and stories that give people a reason to come back.',outputs:['Content direction and calendar','Captions, posts and carousels','Reels and story adaptations','Approved Instagram and Facebook publishing'],input:'Business updates, upcoming occasions, product information and a clear approval contact.',measure:'Publishing activity, content response and available customer interactions.',example:'A showroom answers the questions customers ask in store, then introduces new arrivals through the same familiar voice.'},
{slug:'local-discovery',cat:'Cat Radar',name:'Local discovery',short:'Be there when they look.',icon:'radar',description:'When someone hears your name, make the next step easy. Clear business information, current photos and useful updates help people find their way to you.',outputs:['Google Business Profile information review','Business photos and relevant updates','Clear product and service information','Contact, opening-hour and direction checks'],input:'Access to an eligible business profile and accurate contact, service and opening information.',measure:'Available profile interactions, information accuracy and useful customer actions.',example:'Someone sees your reel, searches your name, checks your opening hours and finds directions without a second thought.'},
{slug:'local-campaigns',cat:'Cat Signal',name:'Local campaigns',short:'Get the right people curious.',icon:'signal',description:'A relevant message for the people you can actually serve. We connect local audiences with useful offers, new openings and reasons to enquire.',outputs:['Local audience and message planning','Meta campaign creative and setup','Launch, offer and enquiry campaigns','Response review and campaign adjustments'],input:'A clear offer or objective, service area, approved creative and a team ready to respond to enquiries.',measure:'Tracked responses and enquiry quality, with confirmed bookings or sales provided by your team.',example:'A fitness studio introduces a beginner session to people in its service area, with one clear invitation to enquire.'},
{slug:'creator-collaborations',cat:'Cat Circle',name:'Creator connections',short:'Let local people tell your story.',icon:'circle',description:'The right local voice can make an introduction feel natural. We bring suitable creators, thoughtful ideas and your business together.',outputs:['Relevant local creator selection','Collaboration concepts and briefs','Visit and content coordination','Available performance and response review'],input:'Your audience, business experience, preferred message and availability for a creator visit.',measure:'Content performance, audience relevance and feedback from customers and your team.',example:'A local food creator explores what makes your café worth a visit, with your people and signature dish at the heart of the story.'}
];
export const industries=[
{id:'food',name:'Food & cafés',label:'a café or restaurant',icon:'food',headline:'Make your next regular a local.',idea:'Meet the dish. Meet the maker.',detail:'Film the chef preparing a signature dish. Let the story end with a clear invitation to visit.',cta:'Discover your next favourite, just around the corner.',focus:'Signature dishes, your people and the experience of visiting.',color:'orange'},
{id:'retail',name:'Retail & showrooms',label:'a shop or showroom',icon:'retail',headline:'Give the neighbourhood a reason to drop in.',idea:'New in. Right nearby.',detail:'Show one new arrival in use and answer the question a customer would ask in store.',cta:'Come take a closer look.',focus:'New arrivals, product demonstrations and reasons to visit.',color:'purple'},
{id:'beauty',name:'Beauty & wellness',label:'a beauty or wellness business',icon:'beauty',headline:'A familiar face before the first appointment.',idea:'Your first visit, explained.',detail:'Introduce a team member and walk through what a first appointment feels like.',cta:'Ask us about your first appointment.',focus:'Service explainers, real people and genuine customer experiences.',color:'pink'},
{id:'fitness',name:'Fitness & sports',label:'a fitness or sports business',icon:'fitness',headline:'Help the next beginner feel at home.',idea:'Everyone starts somewhere.',detail:'Follow a trainer through a beginner-friendly session and explain what to expect.',cta:'Enquire about trying a session.',focus:'Trainer introductions, classes and welcoming first experiences.',color:'green'},
{id:'education',name:'Education & training',label:'an institute or training centre',icon:'education',headline:'Turn local curiosity into a conversation.',idea:'A question worth answering.',detail:'Ask a teacher to answer one common course question and show the learning environment.',cta:'Talk to us about your next step.',focus:'Course clarity, faculty introductions and learning experiences.',color:'purple'},
{id:'services',name:'Local services',label:'a local service business',icon:'services',headline:'Be the name they know to call.',idea:'Here is how we help.',detail:'Demonstrate a useful service, explain the problem it solves and show the areas you cover.',cta:'Tell us what you need help with.',focus:'Practical demonstrations, clear service areas and customer questions.',color:'orange'}];
export const goals=[{id:'visits',name:'More local visits',services:[3,1,4]},{id:'enquiries',name:'More enquiries',services:[0,1,4]},{id:'launch',name:'A new opening',services:[0,1,5]},{id:'presence',name:'A stronger online presence',services:[2,1,3]}];
export const faqs=[['What does hyperlocal marketing mean?','It means focusing on the neighbourhoods, towns and communities your business can realistically serve. We connect your products, stories and services with relevant nearby audiences.'],['What kind of businesses do you work with?','The approach suits retail, food and hospitality, beauty and wellness, fitness, education and local service businesses. Your location and goals help shape the work.'],['Can you create content in Malayalam?','Malayalam or relevant bilingual communication can be part of the content direction. We agree the language and tone around your business and audience.'],['What happens after I send a brief?','Your brief is saved for review. The next conversation clarifies your location, priorities, required services and working arrangements. Timing and scope are confirmed with you.'],['Will I approve content before it is published?','Yes. The working process includes internal review and a client approval stage before publishing. The exact version and any requested changes should be clearly recorded.'],['How do you measure progress?','We review work completed, available content and campaign response, and feedback from your team. Bookings or sales need confirmation from your business; an enquiry is not automatically a sale.']];
export const articles=[
{slug:'what-hyperlocal-marketing-means',type:'THE LOCAL BASICS',time:'2 min read',title:'Your best audience might be closer than you think.',intro:'What hyperlocal marketing means for a business with real doors, real people and a neighbourhood to serve.',sections:[['Start with the people you can serve','Think about where your customers come from, how far they will travel and why they choose you. A neighbourhood café and a specialist service may have very different catchments.'],['Give people something specific to recognise','Show the people, products and details that make your business yours. A familiar language, useful answer or recognisable local setting can help a story feel relevant.'],['Make the next step easy','Keep opening hours, contact information and directions clear. Connect your content to an action that fits the business: an enquiry, a booking request or a visit.'],['Learn from actual conversations','Ask the team what people enquire about and which responses turn into real customer actions. Use those observations to improve the next activity.']]},
{slug:'prepare-for-a-content-shoot',type:'A LITTLE PREPARATION',time:'2 min read',title:'A good shoot starts before the camera arrives.',intro:'A simple checklist to help your team make the most of a business content shoot.',sections:[['Choose the story','Agree which product, service or experience matters most. Write down the three questions customers ask about it.'],['Prepare the space and people','Have the relevant products ready, tidy the areas that will appear on camera and tell participating team members what the shoot is about.'],['Bring the right details','Confirm names, product information, current availability and the correct contact details. Arrange consent for anyone sharing a testimonial.'],['Agree who reviews the work','Choose a clear approval contact and consolidate feedback. Check the message and factual details as carefully as the visuals.']]},
{slug:'from-enquiry-to-customer',type:'BETTER CONVERSATIONS',time:'2 min read',title:'Someone enquired. What happens next?',intro:'The way a business responds matters as much as the message that brought someone in.',sections:[['Make responsibility clear','Assign a person to respond to incoming enquiries. Keep the context from the campaign or form so customers do not need to explain everything again.'],['Answer the actual question','Understand what they need before sending a long general response. Confirm availability, the next step and any information they need to make a decision.'],['Keep a simple record','Track enquiry source, requirement, follow-up and the eventual outcome. Distinguish interested conversations from confirmed appointments or sales.'],['Share what you learn','Tell your marketing team which enquiries were relevant and what questions came up. That feedback helps the next campaign speak more clearly.']]},
{slug:'local-launch-checklist',type:'OPENING SOON',time:'2 min read',title:'Give your opening a proper local introduction.',intro:'The details that make a new business easier to discover and visit.',sections:[['Make the essentials easy to find','Confirm your name, location, opening date, hours and contact information. Use the same accurate details across your public pages.'],['Show what is arriving','Introduce your space and people, then explain what customers can expect. Create a reason for someone nearby to be curious.'],['Coordinate the introduction','Plan your content, local promotions and any creator visit together. Give each activity a clear role and next action.'],['Prepare for the response','Make sure the team knows what has been promoted and can answer enquiries. Review customer feedback after opening to decide what to show next.']]}];
export const checks=[
{q:'Can someone find accurate details about your business?',hint:'Your contact, location or service area and opening hours are easy to find.',action:'Check your business name, contact details, hours and directions across your public profiles.',service:3},
{q:'Have you shared real, recent content from your business?',hint:'Your products, your people or an actual customer experience.',action:'Plan one useful story showing your actual product, people or business experience.',service:1},
{q:'Is it clear what you offer and who it is for?',hint:'A new visitor can understand your main products or services.',action:'Write a simple introduction explaining what you do and who you help.',service:0},
{q:'Can people see genuine reasons to trust you?',hint:'Real work, useful demonstrations or customer stories shared with consent.',action:'Choose a real demonstration or approved customer story that gives people confidence.',service:1},
{q:'Does your content make the next step easy?',hint:'People know whether to enquire, ask for directions or request an appointment.',action:'Add one clear next step to your profile and relevant content.',service:2},
{q:'Does your team record and follow up enquiries?',hint:'Someone owns the response and knows what happened next.',action:'Agree who handles enquiries and how the team records the outcome.',service:4}];
