import Link from 'next/link';
import {notFound} from 'next/navigation';
import {industries,services} from '@/lib/content';
import {industryPages} from '@/lib/industry-pages';
import {IndustryExperience} from '@/components/industry-experiences';
import {PageIntro,CatIcon} from '@/components/shared';
import {Button} from '@/components/ui/button';
import {ArrowUpRight} from 'lucide-react';
export function generateStaticParams(){return industries.map(i=>({id:i.id}))}
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params;const i=industries.find(x=>x.id===id);return {title:i?`Local Marketing for ${i.name} — Viral Cat`:'Your business',description:industryPages[id]?.intro,alternates:{canonical:'/your-business/'+id}}}
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const i=industries.find(x=>x.id===id),detail=industryPages[id];if(!i||!detail)notFound();return <div className={"industry-route industry-route-"+id}><PageIntro eyebrow={i.name.toUpperCase()} title={i.headline} description={detail.intro}/><section className="container detail-grid content-area"><div className={'concept-block '+i.color}><span className="quiet-caption">Here’s one idea</span><CatIcon name={i.icon} size={54}/><h2>{i.idea}</h2><p>{i.detail}</p><strong>{i.cta}</strong><Link href={'/work/'+id} className="text-link">Explore the sample project <ArrowUpRight size={17}/></Link></div><div className="detail-stack"><article><h3>Start with what matters.</h3><ul className="industry-priorities">{detail.priorities.map(p=><li key={p}>{p}</li>)}</ul></article><article><h3>Bring the details.</h3><p>{detail.inputs.join('. ')}.</p></article><Button asChild className="button purple"><Link href={'/contact?industry='+i.id}>Build a brief for my business <ArrowUpRight/></Link></Button></div></section><IndustryExperience id={id}/><section className="section container"><div className="section-heading"><div><h2>Three ideas.<br/><em>A useful beginning.</em></h2></div></div><div className="editorial-card-grid">{detail.stories.map((s,n)=><article key={s}><p className="industry-story-idea">{s}</p></article>)}</div></section><section className="container related-section"><h2>A useful starting mix.</h2><div className="related-links">{detail.mix.map(slug=>services.find(s=>s.slug===slug)!).map(s=><Link key={s.slug} href={'/services/'+s.slug}><CatIcon name={s.icon}/><span>{s.name}</span><ArrowUpRight size={18}/></Link>)}</div></section><section className="container section industry-question"><h2>{detail.question}</h2><p>{detail.answer}</p><Link className="text-link" href={'/contact?industry='+id}>Tell us about your business <ArrowUpRight size={18}/></Link></section></div>}
